services:
  mindcode-front:
    container_name: mindcode-front
    image: node:23-alpine3.20
    working_dir: /usr/src/app
    volumes:
      - ./front:/usr/src/app
    ports:
      - 5173:3000
    tmpfs:
      - /tmp
    restart: always
    command: sh -c "npm install && npm run build && npm run start"

  mindcode-back:
    image: node:23-alpine3.20
    container_name: mindcode-back
    working_dir: /usr/src/app
    volumes:
      - ./back:/usr/src/app
    ports:
      - 3000:3000
    tmpfs:
      - /tmp
    restart: always
    command: sh -c "cp .env.prod .env && npm install && node index.js"
    links:
      - mindcode-mysql
      - mindcode-mongo

  mindcode-mongo:
    container_name: mindcode-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mindcode-mongo-db:/data/db

  mindcode-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mindcode-mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mindcode-mongo

  mindcode-mysql:
    image: mysql:9.2
    container_name: mindcode-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: mindcode
    volumes:
      - mindcode-mysql-db:/var/lib/mysql:rw 
      - ./db/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./db/inserts.sql:/docker-entrypoint-initdb.d/inserts.sql

  mindcode-adminer:
    image: adminer:4.8.1-standalone
    container_name: mindcode-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mindcode-mysql

volumes:
  mindcode-mongo-db:
  mindcode-mysql-db:
